### ISSUE TITLE
vkreplay gets validation errors playing back a trace of Hologram

### ISSUE THREAD

**Issue by Tony-LunarG** [LunarG/VulkanTools#100]
There are no validation  errors when tracing Hologram, but when playing the trace back, I see:

Swapchain(ERROR): object: 0x19e0440 type: 3 location: 1643 msgCode: 8: vkCreateSwapchainKHR() called with pCreateInfo->imageExtent = (1280,1024), which is not equal to the currentExtent = (100,100) returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR().
ObjectTracker(ERROR): object: 0x5 type: 5 location: 331 msgCode: -1: Invalid Semaphore Object 0x5. 
ObjectTracker(ERROR): object: 0x5 type: 0 location: 310 msgCode: 1: Unable to remove Semaphore obj 0x5. Was it created? Has it already been destroyed?
ObjectTracker(ERROR): object: 0x5 type: 5 location: 331 msgCode: -1: Invalid Semaphore Object 0x5. 
ObjectTracker(ERROR): object: 0x5 type: 0 location: 310 msgCode: 1: Unable to remove Semaphore obj 0x5. Was it created? Has it already been destroyed?
ObjectTracker(ERROR): object: 0x5 type: 5 location: 331 msgCode: -1: Invalid Semaphore Object 0x5. 
ObjectTracker(ERROR): object: 0x5 type: 0 location: 310 msgCode: 1: Unable to remove Semaphore obj 0x5. Was it created? Has it already been destroyed?
ObjectTracker(ERROR): object: 0x4 type: 5 location: 343 msgCode: 3: OBJ ERROR : For device 0x19e0440, Semaphore object 0x4 has not been destroyed.
ObjectTracker(ERROR): object: 0x2 type: 5 location: 343 msgCode: 3: OBJ ERROR : For device 0x19e0440, Semaphore object 0x2 has not been destroyed.
ObjectTracker(ERROR): object: 0x1 type: 5 location: 343 msgCode: 3: OBJ ERROR : For device 0x19e0440, Semaphore object 0x1 has not been destroyed.

16.04, Haswell, Mesa driver, SDK-1.0.30

**Comment by mizhen** [comment]
Hi Tony, when capture Hologram to get this trace,  the page guard enabled or not?

**Comment by Tony-LunarG** [comment]
It was Linux, and I don't think we have page guard on Linux yet.

**Comment by stroyan** [comment]
This is a result of not removing mappings for most object types in vkDestroy* calls.
vktrace/vktrace_generate.py
#TODO make sure vkDestroy object functions really do clean up the object maps

**Comment by Tony-LunarG** [comment]
New with sdk-1.0.33 - Now I get many many of:

MEM(ERROR): object: 0x0 type: 0 location: 11277 msgCode: 645: vkFlushMappedMemoryRanges: Size in pMemRanges[0] is 0x19064, which is not a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize (0x40). For more information refer to Vulkan Spec Section '10.2.1. Host Access to Device Memory Objects' which states 'If size is not equal to VK_WHOLE_SIZE, size must be a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#VkMappedMemoryRange)
MEM(ERROR): object: 0x0 type: 0 location: 11270 msgCode: 644: vkFlushMappedMemoryRanges: Offset in pMemRanges[0] is 0xaf2bc, which is not a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize (0x40). For more information refer to Vulkan Spec Section '10.2.1. Host Access to Device Memory Objects' which states 'offset must be a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#VkMappedMemoryRange)

This could be due to new validation, new Mesa driver or new vktrace code.

**Comment by Tony-LunarG** [comment]
Ignore the above comment - I've fixed Hologram to use nonCoherentAtomSize when flushing mapped memory.

**Comment by davidlunarg** [comment]
I only see one validation error when replaying a trace of Hologram:

Swapchain(ERROR): object: 0x2680c40 type: 3 location: 11684 msgCode: 8: vkCreateSwapchainKHR() called with pCreateInfo->imageExtent = (1280,1024), which is not equal to the currentExtent = (100,100) returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR().

**Comment by Tony-LunarG** [comment]
More investigation shows that the Mesa driver always returns 0x1 as the handle when you create a semaphore.  Every semaphore created will have handle 1.  Hologram creates and destroys 4 semaphores.  When api_dumping the Hologram program, I see 4 calls to DestroySemphore, all with handle 1, all with no validation errors.  When I api_dump the playback of a Hologram trace, I see one call to DestroySemaphore with handle 1 and no validation errors, then 3 more calls to DestroySemaphore, all with handle ZERO, and each of those gets a validation error.  All four calls to DestroySemaphore should be using handle 1.

**Comment by Tony-LunarG** [comment]
I'm not seeing this in my SDK-1.0.42 testing.  Mesa 13.0.4 may have fixed it?

**Comment by eero-t** [comment]
Tried latest DOTA2, VulkanTools & Mesa from git.

Of the 3 traces I took, in 2 I still see semaphore errors, but less than earlier.  These happen when Tutorial starts and when it ends:
```
ObjectTracker(ERROR): object: 0x9cf8 type: 5 location: 374 msgCode: 1956: Invalid Semaphore Object 0x9cf8. For more information refer to Vulkan Spec Section '30.6. WSI Swapchain' which states 'If semaphore is not VK_NULL_HANDLE, semaphore must be a valid VkSemaphore handle' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#vkAcquireNextImageKHR)
ObjectTracker(ERROR): object: 0x9cf8 type: 5 location: 374 msgCode: 203: Invalid Semaphore Object 0x9cf8. For more information refer to Vulkan Spec Section '6.3. Semaphores' which states 'If semaphore is not VK_NULL_HANDLE, semaphore must be a valid VkSemaphore handle' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#vkDestroySemaphore)
ObjectTracker(ERROR): object: 0x9cf8 type: 0 location: 328 msgCode: 1: Unable to remove Semaphore obj 0x9cf8. Was it created? Has it already been destroyed?
ObjectTracker(ERROR): object: 0xad99 type: 5 location: 374 msgCode: 146: Invalid Semaphore Object 0xad99. For more information refer to Vulkan Spec Section '5.4. Command Buffer Submission' which states 'If waitSemaphoreCount is not 0, pWaitSemaphores must be a pointer to an array of waitSemaphoreCount valid VkSemaphore handles' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#VkSubmitInfo)
```

Similar errors are visible also when replaying trace of e.g. Sacha Willems' Vulkan demos (e.g. "bloom" or "raytracing"), when the trace ends, or it's looped.  Such validation errors aren't printed when one runs the demos directly, so this seems to be replay issue.

During DOTA2 startup and Tutorial, I see also lot of these:
```
DS(ERROR): object: 0x25c5f type: 5 location: 4545 msgCode: 78: Queue 0x0xa55960 is waiting on semaphore 0x25c5f that has no way to be signaled.
DS(ERROR): object: 0x25d31 type: 5 location: 4545 msgCode: 78: Queue 0x0xa55960 is waiting on semaphore 0x25d31 that has no way to be signaled.
DS(ERROR): object: 0x25dfb type: 5 location: 4545 msgCode: 78: Queue 0x0xa55960 is waiting on semaphore 0x25dfb that has no way to be signaled.
```

**Comment by eero-t** [comment]
Semaphore issue still happen with latest Mesa, VulkanTools and .e.g Sacha Willems' Vulkan demos git versions, only in tracing, not when running the demos directly.

**Comment by davidlunarg** [comment]
I can no longer reproduce this issue. Will close.
